### ISSUE TITLE
Fehler beim Snaptshot

### ISSUE THREAD

**Issue by Nall-chan** [Wolbolar/IPSymconDoorbird#2]
Es wird nicht geprüft ob eine Objekt mit dem Ident existiert.
Zeile 1464

Dadurch Folgefehler wie umbenennen der Hauptkategorie 0

**Comment by Wolbolar** [comment]
Habe ich was geändert, meinst das reicht damit der Fehler nicht mehr auftritt?

**Comment by Nall-chan** [comment]
1486 wird IPS_GetObjectIDByIdent genutzt ohne anschließende Prüfung ob Objekt vorhanden.
Warum hast du da gefühlt 5 mal den gleichen Code um MediaObjekte zu erzeugen ?
Lagere das doch einfach in eine eigene Funktion aus. Dann musst du Fehler nicht 5x korrigieren.

**Comment by Wolbolar** [comment]
Im Prinzip wird vorher schon geprüft ob überhaupt etwas in der Kategorie vorhanden ist. Wenn da nichts vorhanden sein sollte, sollte jetzt IPS_GetObjectIDByIdent auch nicht mehr aufgerufen werden und in der Folge dann auch nicht weiter verarbeitet.

Was würdest Du denn alles an Code zusammenfassen bei den Media Objekten?

**Comment by Nall-chan** [comment]
Keine Ahnung, habe es mir nicht im Detail angeschaut.


Am 14. Januar 2018 20:43:27 MEZ schrieb Fonzo <notifications@github.com>:
>Im Prinzip wird vorher schon geprüft ob überhaupt etwas in der
>Kategorie vorhanden ist. Wenn da nichts vorhanden sein sollte, sollte
>jetzt IPS_GetObjectIDByIdent auch nicht mehr aufgerufen werden und in
>der Folge dann auch nicht weiter verarbeitet.
>
>Was würdest Du denn alles an Code zusammenfassen bei den Media
>Objekten?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Wolbolar/IPSymconDoorbird/issues/2#issuecomment-357536459

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
